export const managerRoutes = {
  home: "/",
  manageRentals: "/manage-rentals",
  manageRentalStatus: "/manage-rental-status",
  equipmentAvailability: "/equipment-availability",
  checkDevice: "/check-device",
  orderHistory: "/order-history",
  workAssignment: "/work-assignment",
  deliveryOrder: "/delivery-order",
  manageOrders: "/manage-orders",
  depositConfirmation: "/deposit-confirmation",
  customerChat: "/chat",
  feedback: "/feedback",
  paymentManagement: "/payment-management",
  repairRequests: "/repair-request",
  equipmentConditionLog: "/equipment-condition-log",
  equipmentStatusReport: "/equipment-status-report",
  feedbackManagement: "/feedback-management",
  manageReplacement: "/manage-replacement",
};

export const adminRoutes = {
  dashboard: "/dashboard",
  feedbackDetail: "/dashboard/feedback/:id",
  feedback: "/dashboard/feedback",
  tableHotPotCombo: "/dashboard/hotpotCombo",
  createHotPotCombo: "/dashboard/createCombo",
  profile: "/profile",
  tableIngredients: "/dashboard/ingredients",
  createIngredients: "/dashboard/createIngredients",
};
